spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/editor_nice
    username: root
    password: "!junki123"

  jpa:
    properties:
      hibernate:
        #        show-sql: 'true'
        format_sql: 'true'
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: create
    open-in-view: false