spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/editor_nice
    username: root
    password:

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: update
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug  # 로그