SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE MEMBER;
TRUNCATE TABLE BOARD;
TRUNCATE TABLE CATEGORY;
TRUNCATE TABLE COMMENT;
TRUNCATE TABLE COMPANY;
TRUNCATE TABLE EMPLOYER;
TRUNCATE TABLE JOB_SEEKER;
TRUNCATE TABLE WISH_LIST;
TRUNCATE TABLE EVALUATION;
TRUNCATE TABLE INTERVIEW_OFFER;
TRUNCATE TABLE RESUME;
TRUNCATE TABLE GENRE;
TRUNCATE TABLE RESUME_GENRE;
TRUNCATE TABLE SKILL;
TRUNCATE TABLE RESUME_SKILL;
TRUNCATE TABLE JOB_EXPERIENCE;
TRUNCATE TABLE PORTFOLIO_VIDEO;

SET REFERENTIAL_INTEGRITY TRUE;